/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TuTruongSoRouteImport } from './routes/tu-truong-so'
import { Route as BatTuRouteImport } from './routes/bat-tu'
import { Route as BatCucLinhSoRouteImport } from './routes/bat-cuc-linh-so'
import { Route as IndexRouteImport } from './routes/index'

const TuTruongSoRoute = TuTruongSoRouteImport.update({
  id: '/tu-truong-so',
  path: '/tu-truong-so',
  getParentRoute: () => rootRouteImport,
} as any)
const BatTuRoute = BatTuRouteImport.update({
  id: '/bat-tu',
  path: '/bat-tu',
  getParentRoute: () => rootRouteImport,
} as any)
const BatCucLinhSoRoute = BatCucLinhSoRouteImport.update({
  id: '/bat-cuc-linh-so',
  path: '/bat-cuc-linh-so',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bat-cuc-linh-so': typeof BatCucLinhSoRoute
  '/bat-tu': typeof BatTuRoute
  '/tu-truong-so': typeof TuTruongSoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bat-cuc-linh-so': typeof BatCucLinhSoRoute
  '/bat-tu': typeof BatTuRoute
  '/tu-truong-so': typeof TuTruongSoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bat-cuc-linh-so': typeof BatCucLinhSoRoute
  '/bat-tu': typeof BatTuRoute
  '/tu-truong-so': typeof TuTruongSoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bat-cuc-linh-so' | '/bat-tu' | '/tu-truong-so'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bat-cuc-linh-so' | '/bat-tu' | '/tu-truong-so'
  id: '__root__' | '/' | '/bat-cuc-linh-so' | '/bat-tu' | '/tu-truong-so'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatCucLinhSoRoute: typeof BatCucLinhSoRoute
  BatTuRoute: typeof BatTuRoute
  TuTruongSoRoute: typeof TuTruongSoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tu-truong-so': {
      id: '/tu-truong-so'
      path: '/tu-truong-so'
      fullPath: '/tu-truong-so'
      preLoaderRoute: typeof TuTruongSoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bat-tu': {
      id: '/bat-tu'
      path: '/bat-tu'
      fullPath: '/bat-tu'
      preLoaderRoute: typeof BatTuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bat-cuc-linh-so': {
      id: '/bat-cuc-linh-so'
      path: '/bat-cuc-linh-so'
      fullPath: '/bat-cuc-linh-so'
      preLoaderRoute: typeof BatCucLinhSoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatCucLinhSoRoute: BatCucLinhSoRoute,
  BatTuRoute: BatTuRoute,
  TuTruongSoRoute: TuTruongSoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
